# Project Configuration
[PROJECT]
NAME = ""  # Project name, to be overridden in local settings
ROOT_IDENTIFIER = "README.md"

# Server Configuration
[SERVER]
PORT = 8000
HOST = "0.0.0.0"  # Default to all interfaces
RELOAD = true
LOG_LEVEL = "info"  # Default log level

# Logging Configuration
[LOGGING]
FORMAT = "%(asctime)s - %(levelname)s - %(message)s"

# Environment Variables
[ENV]
APP_ENV = "lcl"  # Default environment, can be overridden
DEBUG = false  # Default debug mode, can be overridden

# Placeholder sections for extended configurations
[BACKUP]
[NGROK]
[VSCODE]
[CORS]
[DATABASE]

