"""Chat Collection table's per user uniqueness of chat constraint removed

Revision ID: 9c7f1cdc05c6
Revises: 009052d56aa1
Create Date: 2024-12-30 05:44:36.688047+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7f1cdc05c6'
down_revision: Union[str, None] = '009052d56aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_collection_per_user', 'chat_collections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_collection_per_user', 'chat_collections', ['user_email', 'collection_name'])
    # ### end Alembic commands ###
