"""Relationship changed

Revision ID: 530b1125ef44
Revises: dcee31ccd9f0
Create Date: 2024-10-28 04:50:06.950240+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530b1125ef44'
down_revision: Union[str, None] = 'dcee31ccd9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts_backup')
    op.create_foreign_key(None, 'attachments', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'deleted', name='conversation_status'),
               server_default=None,
               nullable=True)
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('edit_history', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.alter_column('messages', 'has_artifact',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'has_artifact',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_column('messages', 'message_metadata')
    op.drop_column('messages', 'edit_history')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'is_edited')
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'deleted', name='conversation_status'),
               server_default=sa.text("'active'::conversation_status"),
               nullable=False)
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_table('artifacts_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artifact_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parent_artifact_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
