"""msg metadata column added in Conversations table

Revision ID: 009052d56aa1
Revises: 4b25c760e0d5
Create Date: 2024-12-26 05:32:10.694715+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009052d56aa1'
down_revision: Union[str, None] = '4b25c760e0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('message_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'message_metadata')
    # ### end Alembic commands ###
