"""changes in attachments table's file type field

Revision ID: a6b0628db0fc
Revises: 3bcf532d9f38
Create Date: 2024-11-05 09:48:23.468956+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b0628db0fc'
down_revision: Union[str, None] = '3bcf532d9f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_type',
               existing_type=postgresql.ENUM('media', 'document', 'voice', name='file_type'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_type',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('media', 'document', 'voice', name='file_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
