"""Artifact Fields Updated

Revision ID: 0ddb8165e788
Revises: 530b1125ef44
Create Date: 2024-10-28 05:33:40.390520+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddb8165e788'
down_revision: Union[str, None] = '530b1125ef44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifacts_message_id_key', 'artifacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artifacts_message_id_key', 'artifacts', ['message_id'])
    # ### end Alembic commands ###
