"""platform column type changed in chat collections table

Revision ID: cd005f679f53
Revises: 3d0765962345
Create Date: 2025-01-03 05:21:47.645426+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd005f679f53'
down_revision: Union[str, None] = '3d0765962345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_collections', 'platform',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_collections', 'platform',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
