"""platform changed and chat_continue_notification column added in chat collections table

Revision ID: 3d0765962345
Revises: e5ccf64dffa3
Create Date: 2025-01-03 05:19:07.297897+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0765962345'
down_revision: Union[str, None] = 'e5ccf64dffa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_collections', sa.Column('platform_changed', sa.Text(), nullable=True))
    op.add_column('chat_collections', sa.Column('chat_continue_notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_collections', 'chat_continue_notification')
    op.drop_column('chat_collections', 'platform_changed')
    # ### end Alembic commands ###
