"""Create chat admins table with string company type

Revision ID: 40c7f80e05d0
Revises: 19a05d3aecf8
Create Date: 2025-01-08 06:24:06.052501+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c7f80e05d0'
down_revision: Union[str, None] = '19a05d3aecf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_first_name', sa.String(), nullable=False),
    sa.Column('admin_last_name', sa.String(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('admin_password', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assistant_email', sa.String(), nullable=True),
    sa.Column('assistant_email_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_assistant_email_generated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_admins_admin_email'), 'chat_admins', ['admin_email'], unique=True)
    op.create_index(op.f('ix_chat_admins_id'), 'chat_admins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_admins_id'), table_name='chat_admins')
    op.drop_index(op.f('ix_chat_admins_admin_email'), table_name='chat_admins')
    op.drop_table('chat_admins')
    # ### end Alembic commands ###
