"""add_phone_address_to_temp_test

Revision ID: 7e584c4f0d00
Revises: 9a14f75c073f
Create Date: 2024-12-16 13:17:20.221595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e584c4f0d00'
down_revision: Union[str, None] = '9a14f75c073f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_test', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('temp_test', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_test', 'address')
    op.drop_column('temp_test', 'phone_number')
    # ### end Alembic commands ###
