"""add date_of_birth to temp_test

Revision ID: 9a14f75c073f
Revises: 231c6a0d0ace
Create Date: 2024-12-16 13:13:45.337460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a14f75c073f'
down_revision: Union[str, None] = '231c6a0d0ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_test', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_test', 'date_of_birth')
    # ### end Alembic commands ###
